import { StyleSheet } from "react-native";

import { FONT, SIZES, COLORS } from "../../../constants";

const styles = StyleSheet.create({
  container: {
    // marginTop: SIZES.medium,
    // flex: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 15,
    width: "100%",
    height: "100%",
  },
  containerError: {
    height: "110%",
    marginTop: 45,
  },
  createAccountText: {
    color: COLORS.white,
    marginTop: 25,
    textAlign: "center",
    width: "100%",
  },
  errorInput: {
    borderColor: "red",
    borderWidth: 1,
    borderStyle: "solid",
  },
  errorMessage: {
    position: "relative",
    top: -15,
    textAlign: "center",
    color: "red",
    fontWeight: "bold",
    fontSize: SIZES.medium,
    backgroundColor: "rgba(0,0,0,.9)",
    paddingVertical: 15,
    width: "90%",
    borderColor: "red",
    borderWidth: 1,
    borderStyle: "solid",
  },
  inputContainer: {
    flex: 1,
    position: "relative",
    width: "100%",
  },
  inputIcon: {
    position: "absolute",
    right: 35,
    top: 17,
  },
  textInput: {
    paddingVertical: 18,
    paddingHorizontal: 30,
    paddingRight: 72,
    backgroundColor: "rgba(0,0,0,.6)",
    // marginVertical: 8,
    borderRadius: 2,
    color: COLORS.white,
    borderColor: COLORS.white,
    borderWidth: 1,
    borderStyle: "solid",
    fontSize: SIZES.medium,
    fontFamily: FONT.bold,
    // flex: 1,
  },
  loginActions: {
    width: "100%",
    alignItems: "center",
  },
  loginActionsText: {
    width: "100%",
    textAlign: "center",
    marginBottom: 10,
  },
  loginActionsTextInner: {
    color: COLORS.white,
    fontSize: SIZES.medium,
    fontFamily: FONT.bold,
    fontWeight: 900,
    width: "100%",
    textAlign: "center",
    // backgroundColor: '#fff',
    paddingHorizontal: 10,
  },
  loginAltsContainer: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "center",
    justifyContent: "center",
    width: "100%",
    position: "relative",
    // top: 80,
  },
  loginAltIcon: {
    height: 36,
    width: 36,
    resizeMode: "contain",
    marginHorizontal: 15,
  },
  loginBtn: {
    padding: 12,
    marginTop: 0,
    marginBottom: 30,
    marginHorizontal: "auto",
    textAlign: "center",
    color: COLORS.white,
    backgroundColor: COLORS.gaming,
    borderRadius: 3,
    shadowColor: "black",
    shadowOffset: { width: 2, height: 2 },
    shadowRadius: 4,
    shadowOpacity: 0.7,
    width: "100%",
  },
  loginText: {
    color: COLORS.white,
    textAlign: "center",
    fontFamily: FONT.regular,
    fontSize: SIZES.large,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: SIZES.large,
    fontFamily: FONT.medium,
    color: COLORS.primary,
  },
  headerBtn: {
    fontSize: SIZES.medium,
    fontFamily: FONT.medium,
    color: COLORS.gray,
  },
  cardsContainer: {
    marginTop: SIZES.medium,
  },
});

export default styles;
